version: 2.1

workflows:
  WebServerDeployment:
      jobs:
        - packer validate
        - terraform validate
        - packer build:
            requires:
              - packer validate
        - terraform plan and apply:
          requires:
            - packer validate
            - terraform validate and plan
            - packer build
          filters:
            branches:
              only: main
#        - test webserver output:
#          requires:
#            - terraform apply
#          filters:
#              branches:
#                only: main

jobs:
  packer validate:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run:
          name: install ansible
          command: |
            apt-get -y update
            apt-add-repository --yes --update ppa:ansible/ansible
            apt-get install ansible -y
      - run:
          name: packer validate
          command: |
            cd build-image
            packer validate image_build.json

  terraform validate:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: terraform validate
          command: |
            terraform init
            terraform validate

  packer build:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run:
          name: packer build
          command: |
            cd build-image
            packer build image_build.json

  terraform plan and apply:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: terraform plan and apply
          command: |
            terraform init
            terraform plan
            terraform apply -auto-approve