version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  WebServerDeployment:
      jobs:
        - packer validate
        - terraform validate
        - packer build:
            requires:
              - packer validate
        - terraform plan and apply:
            requires:
              - terraform validate
              - packer build
            filters:
              branches:
                only: main
#        - test webserver output:
#          requires:
#            - terraform apply
#          filters:
#              branches:
#                only: main

jobs:
  packer validate:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: build-image/requirements.txt
      - run:
          name: packer validate
          command: |
            cd build-image
            packer validate image_build.json

  terraform validate:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: terraform validate
          command: |
            terraform init
            terraform validate

  packer build:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run:
          name: packer build
          command: |
            cd build-image
            packer build image_build.json

  terraform plan and apply:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: terraform plan and apply
          command: |
            terraform init
            terraform plan
            terraform apply -auto-approve