- name: 'Provision Image'
  hosts: all
  become: true

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        cache_valid_time: 86400 #One day
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: Install Stress
      apt:
        name: stress
        state: present
    - name: Copy index page
      copy:
        src: "./index.html"
        dest: "/var/www/html/index.html"